### PR TITLE
Update mainchain initial blockhash in reorg

### PR DESCRIPTION
**Pull request by olga24912**
update mainchain initial blockhash in reorg if fork starts earlier than the initial block

### CODE REVIEW

**Comment by kiseln** [comment]
We may want to add a test for this scenario

**Comment by karim-en** [comment]
> update mainchain initial blockhash in reorg if fork starts earlier than the initial block

It is an impossible scenario; the initial block hash is like a genesis

**Review by karim-en — CHANGES_REQUESTED** [review]
It is an impossible scenario; the initial block is like a genesis block

**Comment by olga24912** [comment]
> It is an impossible scenario; the initial block is like a genesis block

Theoretically, we could have a long fork, and after garbage collection (GC), we might delete the origin of this fork. In practice, however, for the fork to be that long is unrealistic.

During initialization, such a fork cannot actually occur because when adding the next block, we require that the previous one has already been added.

In practice, yes, I believe this scenario will never happen.

**Comment by kiseln** [comment]
I suppose it can happen if we initialize with a recent block and that block ends up being on the fork chain? Should we add initialization guidelines that specify that we should start with a block with sufficient confirmations?

**Pull request closed without merging**
